In [1]:
import pandas as pd
import numpy as np

In [ ]:
arr = np.arange(10,100,2)
print(arr)
print(type(arr))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
<class 'numpy.ndarray'>


In [ ]:
arr.shape

(45,)

In [ ]:
arr = arr.reshape(5,9)
print(arr)

[[10 12 14 16 18 20 22 24 26]
 [28 30 32 34 36 38 40 42 44]
 [46 48 50 52 54 56 58 60 62]
 [64 66 68 70 72 74 76 78 80]
 [82 84 86 88 90 92 94 96 98]]


In [2]:
import transformers