### Numpy Basic

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr = np.arange(10,100,2)
print(arr)
print(type(arr))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
<class 'numpy.ndarray'>


In [ ]:
arr.shape

(45,)

In [ ]:
arr = arr.reshape(5,9)
print(arr)

[[10 12 14 16 18 20 22 24 26]
 [28 30 32 34 36 38 40 42 44]
 [46 48 50 52 54 56 58 60 62]
 [64 66 68 70 72 74 76 78 80]
 [82 84 86 88 90 92 94 96 98]]


### Transformer

In [3]:
from transformers import pipeline

In [4]:
classifier = pipeline("sentiment-analysis")
classifier("I have been waiting for you my whole life")


No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9991676807403564}]

In [6]:
classifier(
    ["I feel nostalgic when in I go my home.", "I hate this so much!"]
)

[{'label': 'POSITIVE', 'score': 0.9990574717521667},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455}]